targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run
      # `pub run build_runner doctor` to check your config.

      json_serializable:json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generic_argument_factories: true
          ignore_unannotated: false
          include_if_null: true
        generate_for:
          - lib/model/**.dart

      retrofit_generator:retrofit:
        generate_for:
          - lib/client/**.dart
